version: '3'

volumes:
  db_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: foodgram_db
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    image: valera1991/foodgram_backend
    container_name: foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    image: valera1991/foodgram_frontend
    container_name: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: valera1991/foodgram_gateway
    container_name: foodgram_gateway
    ports:
      - 7000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles/
      - media:/app/media
