version: '3'

volumes:
  db_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: pre-production
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/
      - docs:/app/docs/
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/foodgram_static/
      - media:/foodgram_media/
      - docs:/foodgram_docs/api/docs/
