USERNAME_MAX_LENGTH = 150
FIRST_NAME_MAX_LENGTH = 150
SECOND_NAME_MAX_LENGTH = 150
DESCRIPTION_LENGTH = 72
MAX_PASSWORD_LENGTH = 128
RECIPE_NAME_MAX_LENGTH = 256
TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
INGR_NAME_MAX_LENGTH = 128
INGR_MUNIT_MAX_LENGTH = 64
MAX_SIZE_IMG = 2
MAX_URL_SIZE = 256
# admin
MAX_RECIPES = 5
DISPLAY_IMAGE_SIZE = 100
IMAGE_PREVIEW_SIZE = 200
ITEMS_PER_PAGE = 20
