# Generated by Django 3.2.3 on 2025-01-24 09:15

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recipe.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Уникальный псевдоним. Используйте только буквы, цифры и символы @/./+/-/_.', max_length=150, unique=True, validators=[recipe.validators.validate_username], verbose_name='Псевдоним')),
                ('email', models.EmailField(help_text='Адрес электронной почты. Должен быть уникальным.', max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(help_text='Введите имя. Не более 150 символов.', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию. Не более 150 символов.', max_length=150, verbose_name='Фамилия')),
                ('avatar', models.ImageField(default=None, help_text='Загрузите изображение(до 2Мб) для аватарки.', max_length=256, null=True, upload_to='avatars/', validators=[recipe.validators.validate_image_size], verbose_name='Фотография профиля')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ингредиента. Не более 128 символов.', max_length=128, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Единица измерения ингредиента. Не более 64 символов.', max_length=64, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение рецепта(до 2Мб).', max_length=256, upload_to='dishes/', validators=[recipe.validators.validate_image_size], verbose_name='Изображение блюда')),
                ('name', models.CharField(help_text='Название рецепта. Не более 256', max_length=256, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Описание рецепта.', verbose_name='Описание')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Время приготовления в минутах.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='Время приготовления')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания рецепта', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Пользователь добавивший рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-created_at',),
                'default_related_name': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название тега. Не более 32 символов.', max_length=32, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(help_text='Уникальный slug тега, состоящий из латинских букв, цифр и подчеркиваний. Не более 32 символов.', max_length=32, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Количество ингредиента', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipe.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipe.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Компонент блюда',
                'verbose_name_plural': 'Компоненты блюд',
                'ordering': ('recipe',),
                'default_related_name': 'components',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.RecipeComponent', to='recipe.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipe.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='recipe.Recipe', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='recipe.Recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='ingredient_in_recipe'),
        ),
    ]
