# Generated by Django 3.2.3 on 2025-03-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_favorite_recipe',
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
    ]
